[2023-04-25T16:35:28.778+0100] {processor.py:153} INFO - Started process (PID=35379) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:35:28.780+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:35:28.780+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:35:28.780+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:35:28.802+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:35:28.802+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:35:28.802+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:35:28.802+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:35:28.803+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:35:28.810+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-04-25T16:36:20.813+0100] {processor.py:153} INFO - Started process (PID=36870) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:36:20.814+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:36:20.815+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:36:20.814+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:36:20.831+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:36:20.830+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:36:20.831+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:36:20.831+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:36:20.831+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:36:20.839+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-04-25T16:37:08.484+0100] {processor.py:153} INFO - Started process (PID=37885) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:37:08.487+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:37:08.488+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:37:08.488+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:37:08.508+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:37:08.508+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:37:08.509+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:37:08.508+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:37:08.509+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:37:08.518+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-04-25T16:37:54.098+0100] {processor.py:153} INFO - Started process (PID=38984) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:37:54.102+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:37:54.102+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:37:54.102+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:37:54.121+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:37:54.121+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:37:54.121+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:37:54.121+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:37:54.121+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:37:54.129+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-04-25T16:38:43.085+0100] {processor.py:153} INFO - Started process (PID=40098) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:38:43.089+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:38:43.090+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:38:43.090+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:38:43.113+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:38:43.113+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:38:43.114+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:38:43.114+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:38:43.114+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:38:43.127+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-04-25T16:39:33.499+0100] {processor.py:153} INFO - Started process (PID=41248) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:39:33.503+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:39:33.504+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:39:33.503+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:39:33.523+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:39:33.522+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:39:33.523+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:39:33.523+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:39:33.523+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:39:33.531+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-04-25T16:40:23.405+0100] {processor.py:153} INFO - Started process (PID=42408) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:40:23.409+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:40:23.409+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:40:23.409+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:40:23.427+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:40:23.426+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:40:23.427+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:40:23.427+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:40:23.427+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:40:23.436+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-04-25T16:41:07.912+0100] {processor.py:153} INFO - Started process (PID=43379) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:41:07.916+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:41:07.917+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:41:07.917+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:41:07.934+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:41:07.933+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:41:07.934+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:41:07.934+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:41:07.934+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:41:07.942+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-04-25T16:50:53.343+0100] {processor.py:153} INFO - Started process (PID=20195) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:50:53.344+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:50:53.345+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:50:53.345+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:50:53.377+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:50:53.376+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:50:53.377+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:50:53.377+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:50:53.377+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:50:53.391+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2023-04-25T16:51:44.967+0100] {processor.py:153} INFO - Started process (PID=21371) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:51:44.971+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:51:44.972+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:51:44.972+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:51:44.992+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:51:44.991+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:51:44.992+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:51:44.992+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:51:44.993+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:51:45.002+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-04-25T16:52:35.801+0100] {processor.py:153} INFO - Started process (PID=22572) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:52:35.802+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:52:35.803+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:52:35.803+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:52:35.822+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:52:35.822+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:52:35.823+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:52:35.823+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:52:35.823+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:52:35.831+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-04-25T16:53:22.650+0100] {processor.py:153} INFO - Started process (PID=23605) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:53:22.651+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:53:22.651+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:53:22.651+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:53:22.668+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:53:22.668+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:53:22.669+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:53:22.668+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:53:22.669+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:53:22.678+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-04-25T16:54:10.262+0100] {processor.py:153} INFO - Started process (PID=24742) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:54:10.263+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:54:10.264+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:54:10.264+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:54:10.285+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:54:10.284+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:54:10.285+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:54:10.285+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:54:10.285+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:54:10.294+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-04-25T16:55:00.618+0100] {processor.py:153} INFO - Started process (PID=25960) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:55:00.619+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:55:00.620+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:55:00.619+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:55:00.636+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:55:00.636+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:55:00.636+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:55:00.636+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:55:00.637+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:55:00.645+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-04-25T16:55:50.372+0100] {processor.py:153} INFO - Started process (PID=27044) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:55:50.373+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:55:50.373+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:55:50.373+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:55:50.390+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:55:50.389+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:55:50.390+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:55:50.390+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:55:50.390+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:55:50.398+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-04-25T16:56:36.548+0100] {processor.py:153} INFO - Started process (PID=28123) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:56:36.549+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:56:36.550+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:56:36.550+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:56:36.574+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:56:36.574+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:56:36.575+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:56:36.574+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:56:36.575+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:56:36.584+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-04-25T16:57:25.619+0100] {processor.py:153} INFO - Started process (PID=29317) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:57:25.623+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:57:25.624+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:57:25.623+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:57:25.643+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:57:25.642+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:57:25.643+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:57:25.643+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:57:25.644+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:57:25.651+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-04-25T16:58:13.467+0100] {processor.py:153} INFO - Started process (PID=30328) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:58:13.470+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:58:13.471+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:58:13.471+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:58:13.492+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:58:13.491+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:58:13.492+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:58:13.492+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:58:13.492+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:58:13.500+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-04-25T16:58:57.958+0100] {processor.py:153} INFO - Started process (PID=31365) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:58:57.962+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:58:57.964+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:58:57.964+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:58:58.004+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:58:58.003+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:58:58.004+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:58:58.004+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:58:58.005+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:58:58.013+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2023-04-25T16:59:45.813+0100] {processor.py:153} INFO - Started process (PID=32439) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:59:45.816+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T16:59:45.817+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:59:45.817+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:59:45.836+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:59:45.835+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T16:59:45.836+0100] {logging_mixin.py:137} INFO - [2023-04-25T16:59:45.836+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T16:59:45.836+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T16:59:45.845+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-04-25T17:00:33.830+0100] {processor.py:153} INFO - Started process (PID=33593) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:00:33.831+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:00:33.831+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:00:33.831+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:00:33.849+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:00:33.849+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:00:33.850+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:00:33.850+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:00:33.850+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:00:33.859+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-04-25T17:01:22.928+0100] {processor.py:153} INFO - Started process (PID=34659) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:01:22.932+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:01:22.958+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:01:22.958+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:01:23.074+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:01:23.073+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:01:23.076+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:01:23.076+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:01:23.077+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:01:23.120+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.219 seconds
[2023-04-25T17:03:40.593+0100] {processor.py:153} INFO - Started process (PID=38914) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:03:40.595+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:03:40.596+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:03:40.595+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:03:40.615+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:03:40.614+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:03:40.615+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:03:40.615+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:03:40.615+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:03:40.622+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-04-25T17:04:28.208+0100] {processor.py:153} INFO - Started process (PID=40011) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:04:28.212+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:04:28.213+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:04:28.212+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:04:28.229+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:04:28.229+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:04:28.229+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:04:28.229+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:04:28.229+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:04:28.239+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-04-25T17:05:16.319+0100] {processor.py:153} INFO - Started process (PID=41060) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:05:16.322+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:05:16.323+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:05:16.323+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:05:16.341+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:05:16.340+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:05:16.341+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:05:16.341+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:05:16.341+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:05:16.349+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-04-25T17:06:05.322+0100] {processor.py:153} INFO - Started process (PID=42228) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:06:05.323+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:06:05.323+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:06:05.323+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:06:05.340+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:06:05.340+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:06:05.341+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:06:05.340+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:06:05.341+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:06:05.349+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-04-25T17:06:53.732+0100] {processor.py:153} INFO - Started process (PID=43460) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:06:53.736+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:06:53.737+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:06:53.737+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:06:53.765+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:06:53.764+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:06:53.766+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:06:53.766+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:06:53.767+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:06:53.780+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2023-04-25T17:07:48.948+0100] {processor.py:153} INFO - Started process (PID=44807) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:07:48.949+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:07:48.950+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:07:48.950+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:07:48.969+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:07:48.969+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:07:48.970+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:07:48.970+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:07:48.970+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:07:48.979+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-04-25T17:08:37.423+0100] {processor.py:153} INFO - Started process (PID=46271) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:08:37.427+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:08:37.428+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:08:37.427+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:08:37.449+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:08:37.449+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:08:37.450+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:08:37.449+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:08:37.450+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:08:37.459+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-04-25T17:09:23.254+0100] {processor.py:153} INFO - Started process (PID=47428) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:09:23.258+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:09:23.259+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:09:23.259+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:09:23.279+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:09:23.279+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:09:23.280+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:09:23.279+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:09:23.280+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:09:23.290+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-04-25T17:10:14.261+0100] {processor.py:153} INFO - Started process (PID=48609) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:10:14.264+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:10:14.265+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:10:14.265+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:10:14.281+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:10:14.281+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:10:14.282+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:10:14.282+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:10:14.282+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:10:14.290+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-04-25T17:10:59.535+0100] {processor.py:153} INFO - Started process (PID=49802) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:10:59.536+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:10:59.537+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:10:59.536+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:10:59.554+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:10:59.553+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:10:59.554+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:10:59.554+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:10:59.554+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:10:59.562+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-04-25T17:11:46.148+0100] {processor.py:153} INFO - Started process (PID=50754) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:11:46.151+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:11:46.152+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:11:46.152+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:11:46.172+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:11:46.171+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:11:46.172+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:11:46.172+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:11:46.172+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:11:46.180+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-04-25T17:12:38.267+0100] {processor.py:153} INFO - Started process (PID=51952) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:12:38.270+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:12:38.271+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:12:38.271+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:12:38.290+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:12:38.290+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:12:38.290+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:12:38.290+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:12:38.291+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:12:38.299+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-04-25T17:13:25.483+0100] {processor.py:153} INFO - Started process (PID=53196) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:13:25.487+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:13:25.488+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:13:25.487+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:13:25.505+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:13:25.504+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:13:25.505+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:13:25.505+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:13:25.505+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:13:25.513+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-04-25T17:14:13.638+0100] {processor.py:153} INFO - Started process (PID=54173) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:14:13.642+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:14:13.643+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:14:13.643+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:14:13.662+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:14:13.661+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:14:13.662+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:14:13.662+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:14:13.663+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:14:13.670+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-04-25T17:15:04.482+0100] {processor.py:153} INFO - Started process (PID=55396) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:15:04.483+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:15:04.485+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:15:04.484+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:15:04.529+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:15:04.528+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:15:04.529+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:15:04.529+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:15:04.529+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:15:04.540+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2023-04-25T17:15:49.997+0100] {processor.py:153} INFO - Started process (PID=56416) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:15:50.001+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:15:50.002+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:15:50.002+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:15:50.018+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:15:50.018+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:15:50.018+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:15:50.018+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:15:50.019+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:15:50.027+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-04-25T17:16:40.570+0100] {processor.py:153} INFO - Started process (PID=57680) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:16:40.571+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:16:40.572+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:16:40.572+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:16:40.602+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:16:40.601+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:16:40.602+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:16:40.602+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:16:40.602+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:16:40.614+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2023-04-25T17:17:30.132+0100] {processor.py:153} INFO - Started process (PID=59079) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:17:30.136+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:17:30.137+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:17:30.136+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:17:30.156+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:17:30.156+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:17:30.157+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:17:30.157+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:17:30.157+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:17:30.165+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-04-25T17:18:22.008+0100] {processor.py:153} INFO - Started process (PID=60294) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:18:22.012+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:18:22.013+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:18:22.013+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:18:22.032+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:18:22.032+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:18:22.032+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:18:22.032+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:18:22.033+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:18:22.041+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-04-25T17:19:11.095+0100] {processor.py:153} INFO - Started process (PID=61447) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:19:11.102+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:19:11.103+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:19:11.103+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:19:11.124+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:19:11.123+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:19:11.124+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:19:11.124+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:19:11.125+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:19:11.133+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2023-04-25T17:20:01.786+0100] {processor.py:153} INFO - Started process (PID=62659) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:20:01.790+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:20:01.791+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:20:01.790+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:20:01.810+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:20:01.809+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:20:01.810+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:20:01.810+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:20:01.810+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:20:01.819+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-04-25T17:20:51.164+0100] {processor.py:153} INFO - Started process (PID=63713) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:20:51.165+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:20:51.166+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:20:51.165+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:20:51.184+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:20:51.183+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:20:51.184+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:20:51.184+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:20:51.184+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:20:51.192+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-04-25T17:21:41.896+0100] {processor.py:153} INFO - Started process (PID=64882) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:21:41.899+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:21:41.900+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:21:41.900+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:21:41.920+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:21:41.920+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:21:41.921+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:21:41.921+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:21:41.921+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:21:41.931+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-04-25T17:22:28.719+0100] {processor.py:153} INFO - Started process (PID=65970) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:22:28.723+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:22:28.724+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:22:28.723+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:22:28.755+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:22:28.754+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:22:28.755+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:22:28.755+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:22:28.756+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:22:28.773+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2023-04-25T17:23:20.930+0100] {processor.py:153} INFO - Started process (PID=67176) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:23:20.934+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:23:20.935+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:23:20.934+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:23:20.952+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:23:20.951+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:23:20.952+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:23:20.952+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:23:20.952+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:23:20.960+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-04-25T17:24:09.331+0100] {processor.py:153} INFO - Started process (PID=68264) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:24:09.334+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:24:09.335+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:24:09.335+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:24:09.362+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:24:09.361+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:24:09.362+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:24:09.362+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:24:09.363+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:24:09.376+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2023-04-25T17:24:59.787+0100] {processor.py:153} INFO - Started process (PID=69534) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:24:59.790+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:24:59.791+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:24:59.791+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:24:59.807+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:24:59.807+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:24:59.808+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:24:59.807+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:24:59.808+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:24:59.816+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-04-25T17:26:01.065+0100] {processor.py:153} INFO - Started process (PID=71302) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:26:01.066+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:26:01.067+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:26:01.067+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:26:01.109+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:26:01.108+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:26:01.109+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:26:01.109+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:26:01.109+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:26:01.118+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2023-04-25T17:27:14.957+0100] {processor.py:153} INFO - Started process (PID=73192) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:27:14.958+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:27:14.959+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:27:14.958+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:27:14.975+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:27:14.974+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:27:14.975+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:27:14.975+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:27:14.976+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:27:14.984+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-04-25T17:28:05.724+0100] {processor.py:153} INFO - Started process (PID=74602) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:28:05.728+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:28:05.728+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:28:05.728+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:28:05.745+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:28:05.745+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:28:05.746+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:28:05.746+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:28:05.746+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:28:05.754+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-04-25T17:29:16.982+0100] {processor.py:153} INFO - Started process (PID=76337) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:29:16.983+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:29:16.983+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:29:16.983+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:29:17.000+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:29:17.000+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:29:17.000+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:29:17.000+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:29:17.001+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:29:17.008+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-04-25T17:30:19.089+0100] {processor.py:153} INFO - Started process (PID=77759) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:30:19.090+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:30:19.091+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:30:19.090+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:30:19.120+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:30:19.119+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:30:19.120+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:30:19.120+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:30:19.121+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:30:19.130+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-04-25T17:31:12.067+0100] {processor.py:153} INFO - Started process (PID=79052) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:31:12.068+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:31:12.069+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:31:12.069+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:31:12.090+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:31:12.089+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:31:12.090+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:31:12.090+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:31:12.090+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:31:12.099+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-04-25T17:32:22.603+0100] {processor.py:153} INFO - Started process (PID=80618) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:32:22.607+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:32:22.607+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:32:22.607+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:32:22.626+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:32:22.626+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:32:22.626+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:32:22.626+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:32:22.627+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:32:22.635+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-04-25T17:34:01.356+0100] {processor.py:153} INFO - Started process (PID=83011) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:34:01.358+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:34:01.358+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:34:01.358+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:34:01.390+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:34:01.389+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:34:01.390+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:34:01.390+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:34:01.390+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:34:01.399+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2023-04-25T17:36:05.238+0100] {processor.py:153} INFO - Started process (PID=86351) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:36:05.239+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:36:05.240+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:36:05.239+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:36:05.354+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:36:05.354+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:36:05.355+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:36:05.355+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:36:05.355+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:36:05.361+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.127 seconds
[2023-04-25T17:37:11.805+0100] {processor.py:153} INFO - Started process (PID=87949) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:37:11.809+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:37:11.810+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:37:11.810+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:37:11.833+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:37:11.832+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:37:11.833+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:37:11.833+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:37:11.833+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:37:11.842+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-04-25T17:38:04.477+0100] {processor.py:153} INFO - Started process (PID=89205) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:38:04.479+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:38:04.480+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:38:04.480+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:38:04.500+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:38:04.500+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:38:04.501+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:38:04.501+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:38:04.501+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:38:04.518+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-04-25T17:40:28.773+0100] {processor.py:153} INFO - Started process (PID=93255) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:40:28.778+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:40:28.779+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:40:28.779+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:40:28.823+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:40:28.820+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:40:28.823+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:40:28.823+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:40:28.824+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:40:28.840+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2023-04-25T17:42:18.598+0100] {processor.py:153} INFO - Started process (PID=96479) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:42:18.600+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:42:18.600+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:42:18.600+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:42:18.622+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:42:18.621+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:42:18.622+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:42:18.622+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:42:18.622+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:42:18.632+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-04-25T17:44:21.764+0100] {processor.py:153} INFO - Started process (PID=100083) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:44:21.767+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:44:21.768+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:44:21.768+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:44:21.789+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:44:21.788+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:44:21.789+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:44:21.789+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:44:21.789+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:44:21.797+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-04-25T17:45:42.471+0100] {processor.py:153} INFO - Started process (PID=102226) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:45:42.475+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:45:42.475+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:45:42.475+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:45:42.496+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:45:42.495+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:45:42.496+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:45:42.496+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:45:42.497+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:45:42.505+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-04-25T17:48:13.133+0100] {processor.py:153} INFO - Started process (PID=106118) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:48:13.134+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:48:13.135+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:48:13.135+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:48:13.151+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:48:13.151+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:48:13.151+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:48:13.151+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:48:13.152+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:48:13.159+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-04-25T17:49:17.094+0100] {processor.py:153} INFO - Started process (PID=107734) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:49:17.098+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:49:17.099+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:49:17.098+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:49:17.120+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:49:17.120+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:49:17.121+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:49:17.120+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:49:17.121+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:49:17.133+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-04-25T17:51:54.210+0100] {processor.py:153} INFO - Started process (PID=112333) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:51:54.213+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:51:54.215+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:51:54.215+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:51:54.366+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:51:54.365+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:51:54.366+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:51:54.366+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:51:54.367+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:51:54.481+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.277 seconds
[2023-04-25T17:56:16.399+0100] {processor.py:153} INFO - Started process (PID=121110) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:56:16.403+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:56:16.404+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:56:16.404+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:56:16.420+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:56:16.420+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:56:16.421+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:56:16.421+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:56:16.421+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:56:16.429+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-04-25T17:57:12.394+0100] {processor.py:153} INFO - Started process (PID=122665) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:57:12.396+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T17:57:12.396+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:57:12.396+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:57:12.415+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:57:12.414+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T17:57:12.415+0100] {logging_mixin.py:137} INFO - [2023-04-25T17:57:12.415+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T17:57:12.415+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T17:57:12.425+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-04-25T18:02:38.893+0100] {processor.py:153} INFO - Started process (PID=132589) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:02:38.895+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:02:38.895+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:02:38.895+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:02:38.911+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:02:38.910+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:02:38.911+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:02:38.911+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:02:38.911+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:02:38.919+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-04-25T18:03:49.448+0100] {processor.py:153} INFO - Started process (PID=134258) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:03:49.451+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:03:49.453+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:03:49.453+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:03:49.477+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:03:49.476+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:03:49.477+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:03:49.477+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:03:49.478+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:03:49.489+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2023-04-25T18:04:43.895+0100] {processor.py:153} INFO - Started process (PID=135515) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:04:43.896+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:04:43.897+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:04:43.897+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:04:43.919+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:04:43.919+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:04:43.920+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:04:43.919+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:04:43.920+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:04:43.931+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-04-25T18:05:49.704+0100] {processor.py:153} INFO - Started process (PID=137078) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:05:49.705+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:05:49.707+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:05:49.707+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:05:49.722+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:05:49.722+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:05:49.723+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:05:49.723+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:05:49.723+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:05:49.733+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-04-25T18:12:20.202+0100] {processor.py:153} INFO - Started process (PID=147638) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:12:20.205+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:12:20.206+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:12:20.206+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:12:20.226+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:12:20.225+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:12:20.226+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:12:20.226+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:12:20.226+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:12:20.235+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-04-25T18:13:17.450+0100] {processor.py:153} INFO - Started process (PID=148913) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:13:17.451+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:13:17.453+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:13:17.453+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:13:17.488+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:13:17.488+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:13:17.488+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:13:17.488+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:13:17.489+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:13:17.504+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2023-04-25T18:14:31.437+0100] {processor.py:153} INFO - Started process (PID=150721) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:14:31.438+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:14:31.438+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:14:31.438+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:14:31.456+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:14:31.455+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:14:31.456+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:14:31.456+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:14:31.456+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:14:31.465+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-04-25T18:15:44.386+0100] {processor.py:153} INFO - Started process (PID=152260) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:15:44.388+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:15:44.389+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:15:44.388+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:15:44.409+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:15:44.408+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:15:44.409+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:15:44.409+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:15:44.410+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:15:44.422+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-04-25T18:16:40.780+0100] {processor.py:153} INFO - Started process (PID=153589) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:16:40.784+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:16:40.785+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:16:40.785+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:16:40.802+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:16:40.801+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:16:40.802+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:16:40.802+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:16:40.802+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:16:40.811+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-04-25T18:18:41.454+0100] {processor.py:153} INFO - Started process (PID=156341) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:18:41.455+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:18:41.456+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:18:41.456+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:18:41.474+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:18:41.473+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:18:41.474+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:18:41.474+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:18:41.474+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:18:41.483+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-04-25T18:30:36.663+0100] {processor.py:153} INFO - Started process (PID=174596) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:30:36.665+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:30:36.666+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:30:36.665+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:30:36.687+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:30:36.686+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:30:36.688+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:30:36.687+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:30:36.688+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:30:36.699+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-04-25T18:31:29.233+0100] {processor.py:153} INFO - Started process (PID=176004) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:31:29.234+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:31:29.235+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:31:29.235+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:31:29.253+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:31:29.252+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:31:29.253+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:31:29.253+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:31:29.253+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:31:29.261+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-04-25T18:32:44.152+0100] {processor.py:153} INFO - Started process (PID=177784) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:32:44.154+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:32:44.154+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:32:44.154+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:32:44.172+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:32:44.171+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:32:44.172+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:32:44.172+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:32:44.172+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:32:44.180+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-04-25T18:36:40.075+0100] {processor.py:153} INFO - Started process (PID=183905) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:36:40.077+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:36:40.078+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:36:40.077+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:36:40.100+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:36:40.099+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:36:40.100+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:36:40.100+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:36:40.100+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:36:40.110+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-04-25T18:40:23.447+0100] {processor.py:153} INFO - Started process (PID=190731) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:40:23.451+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:40:23.452+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:40:23.452+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:40:23.483+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:40:23.482+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:40:23.485+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:40:23.484+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:40:23.485+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:40:23.507+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2023-04-25T18:41:24.060+0100] {processor.py:153} INFO - Started process (PID=192571) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:41:24.063+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:41:24.064+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:41:24.064+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:41:24.098+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:41:24.098+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:41:24.100+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:41:24.099+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:41:24.103+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:41:24.121+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-04-25T18:43:05.036+0100] {processor.py:153} INFO - Started process (PID=195208) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:43:05.040+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:43:05.041+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:43:05.040+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:43:05.060+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:43:05.060+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:43:05.061+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:43:05.061+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:43:05.061+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:43:05.069+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-04-25T18:43:58.590+0100] {processor.py:153} INFO - Started process (PID=196424) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:43:58.593+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:43:58.594+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:43:58.594+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:43:58.635+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:43:58.634+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:43:58.635+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:43:58.635+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:43:58.636+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:43:58.649+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-04-25T18:48:40.808+0100] {processor.py:153} INFO - Started process (PID=203345) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:48:40.809+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:48:40.810+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:48:40.809+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:48:40.826+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:48:40.825+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:48:40.826+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:48:40.826+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:48:40.827+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:48:40.835+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-04-25T18:49:47.671+0100] {processor.py:153} INFO - Started process (PID=204755) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:49:47.673+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:49:47.675+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:49:47.674+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:49:47.697+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:49:47.696+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:49:47.697+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:49:47.697+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:49:47.697+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:49:47.705+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-04-25T18:50:42.679+0100] {processor.py:153} INFO - Started process (PID=206223) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:50:42.680+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:50:42.681+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:50:42.681+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:50:42.699+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:50:42.699+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:50:42.700+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:50:42.700+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:50:42.700+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:50:42.708+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-04-25T18:51:33.800+0100] {processor.py:153} INFO - Started process (PID=207747) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:51:33.803+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:51:33.805+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:51:33.804+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:51:33.820+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:51:33.820+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:51:33.821+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:51:33.820+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:51:33.821+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:51:33.829+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-04-25T18:52:35.832+0100] {processor.py:153} INFO - Started process (PID=209589) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:52:35.833+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:52:35.834+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:52:35.834+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:52:35.854+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:52:35.853+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:52:35.855+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:52:35.855+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:52:35.855+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:52:35.863+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-04-25T18:53:37.746+0100] {processor.py:153} INFO - Started process (PID=211503) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:53:37.749+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:53:37.751+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:53:37.750+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:53:37.772+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:53:37.771+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:53:37.772+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:53:37.772+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:53:37.772+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:53:37.781+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-04-25T18:54:40.790+0100] {processor.py:153} INFO - Started process (PID=213375) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:54:40.791+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:54:40.792+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:54:40.792+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:54:40.809+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:54:40.808+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:54:40.809+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:54:40.809+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:54:40.809+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:54:40.818+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-04-25T18:55:49.979+0100] {processor.py:153} INFO - Started process (PID=215398) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:55:49.980+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:55:49.981+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:55:49.981+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:55:50.000+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:55:49.999+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:55:50.000+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:55:50.000+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:55:50.000+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:55:50.010+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-04-25T18:57:04.362+0100] {processor.py:153} INFO - Started process (PID=217546) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:57:04.364+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:57:04.365+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:57:04.365+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:57:04.383+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:57:04.382+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:57:04.383+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:57:04.383+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:57:04.384+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:57:04.392+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-04-25T18:58:12.731+0100] {processor.py:153} INFO - Started process (PID=219140) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:58:12.732+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:58:12.733+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:58:12.733+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:58:12.751+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:58:12.750+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:58:12.751+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:58:12.751+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:58:12.752+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:58:12.765+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-04-25T18:59:09.744+0100] {processor.py:153} INFO - Started process (PID=220477) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:59:09.745+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T18:59:09.746+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:59:09.746+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:59:09.763+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:59:09.762+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T18:59:09.763+0100] {logging_mixin.py:137} INFO - [2023-04-25T18:59:09.763+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T18:59:09.763+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T18:59:09.773+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-04-25T19:00:13.143+0100] {processor.py:153} INFO - Started process (PID=221907) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T19:00:13.146+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T19:00:13.147+0100] {logging_mixin.py:137} INFO - [2023-04-25T19:00:13.147+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T19:00:13.166+0100] {logging_mixin.py:137} INFO - [2023-04-25T19:00:13.165+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T19:00:13.166+0100] {logging_mixin.py:137} INFO - [2023-04-25T19:00:13.166+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T19:00:13.166+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T19:00:13.175+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-04-25T19:01:21.677+0100] {processor.py:153} INFO - Started process (PID=223458) to work on /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T19:01:21.678+0100] {processor.py:743} INFO - Processing file /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-25T19:01:21.679+0100] {logging_mixin.py:137} INFO - [2023-04-25T19:01:21.679+0100] {dagbag.py:532} INFO - Filling up the DagBag from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T19:01:21.700+0100] {logging_mixin.py:137} INFO - [2023-04-25T19:01:21.700+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-25T19:01:21.701+0100] {logging_mixin.py:137} INFO - [2023-04-25T19:01:21.700+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-25T19:01:21.701+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-25T19:01:21.713+0100] {processor.py:175} INFO - Processing /home/cavemhan/.local/share/virtualenvs/cyder-test-QPBcvLjc/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
